kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-apic-config-pipeline
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - 'route.openshift.io'
      - ''
    resources:
      - routes
      - secrets